services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DATABASE_DB} -U ${DATABASE_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    command: sh -c "npm run knex:migrate && npm run knex:seed && npm start"
    environment:
      BACKEND_BASE_URL: ${BACKEND_BASE_URL}
      DATABASE_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
      API_PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
