import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
	await knex("plant_stages").del();
	await knex("plants").del();

	await knex("plants").insert([
		{
			id: 1,
			name: "Tomato",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Medium",
			temperature: "18-30°C",
			planting_type: "both",
			image: "tomato.png",
			sunlight: "full",
			care_level: "daily",
			temperature_min: 18,
			temperature_max: 30,
			total_days: 90,
			sowing_depth: 0.5,
			sowing_distance: 60,
			pot_min_depth: 25,
			sowing_period: JSON.stringify(["March", "April", "May"]),
			germination_time: "5-10 days",
			repotting_after: "3-4 weeks",
			total_growth_time: "60-85 days",
		},
		{
			id: 2,
			name: "Cabbage",
			light: "Full sun",
			water: "High",
			difficulty: "Easy",
			temperature: "10-20°C",
			planting_type: "outdoor",
			image: "cabbage.png",
			sunlight: "full",
			care_level: "weekly",
			temperature_min: 10,
			temperature_max: 20,
			total_days: 85,
			sowing_depth: 1.0,
			sowing_distance: 45,
			pot_min_depth: 20,
			sowing_period: JSON.stringify(["April", "May", "June"]),
			germination_time: "4-8 days",
			repotting_after: "4-6 weeks",
			total_growth_time: "80-180 days",
		},
		{
			id: 3,
			name: "Basil",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Easy",
			temperature: "18-30°C",
			planting_type: "both",
			image: "basil.png",
			sunlight: "full",
			care_level: "daily",
			temperature_min: 18,
			temperature_max: 30,
			total_days: 31,
			sowing_depth: 0.3,
			sowing_distance: 25,
			pot_min_depth: 15,
			sowing_period: JSON.stringify(["April", "May", "June"]),
			germination_time: "5-10 days",
			repotting_after: "3-4 weeks",
			total_growth_time: "20-30 days",
		},
		{
			id: 4,
			name: "Lettuce",
			light: "Partial shade",
			water: "High",
			difficulty: "Easy",
			temperature: "10-20°C",
			planting_type: "outdoor",
			image: "lettuce.png",
			sunlight: "partial",
			care_level: "daily",
			temperature_min: 10,
			temperature_max: 20,
			total_days: 45,
			sowing_depth: 0.5,
			sowing_distance: 30,
			pot_min_depth: 15,
			sowing_period: JSON.stringify(["March", "April", "May", "June"]),
			germination_time: "2-8 days",
			repotting_after: "3-4 weeks",
			total_growth_time: "30-70 days",
		},
		{
			id: 5,
			name: "Strawberry",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Medium",
			temperature: "15-25°C",
			planting_type: "both",
			image: "strawberry.png",
			sunlight: "full",
			care_level: "daily",
			temperature_min: 15,
			temperature_max: 25,
			total_days: 66,
			sowing_depth: 0.3,
			sowing_distance: 35,
			pot_min_depth: 20,
			sowing_period: JSON.stringify(["February", "March", "April"]),
			germination_time: "14-21 days",
			repotting_after: "6-8 weeks",
			total_growth_time: "60-90 days",
		},
		{
			id: 6,
			name: "Carrot",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Easy",
			temperature: "10-25°C",
			planting_type: "outdoor",
			image: "carrot.png",
			sunlight: "full",
			care_level: "weekly",
			temperature_min: 10,
			temperature_max: 25,
			total_days: 70,
			sowing_depth: 0.5,
			sowing_distance: 10,
			pot_min_depth: 30,
			sowing_period: JSON.stringify(["April", "May", "June"]),
			germination_time: "10-21 days",
			repotting_after: "N/A",
			total_growth_time: "50-80 days",
		},
		{
			id: 7,
			name: "Mint",
			light: "Partial shade",
			water: "High",
			difficulty: "Easy",
			temperature: "15-25°C",
			planting_type: "both",
			image: "mint.png",
			sunlight: "partial",
			care_level: "daily",
			temperature_min: 15,
			temperature_max: 25,
			total_days: 55,
			sowing_depth: 0.5,
			sowing_distance: 45,
			pot_min_depth: 25,
			sowing_period: JSON.stringify(["April", "May", "June"]),
			germination_time: "10-15 days",
			repotting_after: "4-6 weeks",
			total_growth_time: "60-90 days",
		},
		{
			id: 8,
			name: "Spinach",
			light: "Partial shade",
			water: "High",
			difficulty: "Easy",
			temperature: "5-20°C",
			planting_type: "outdoor",
			image: "spinach.png",
			sunlight: "partial",
			care_level: "daily",
			temperature_min: 5,
			temperature_max: 20,
			total_days: 45,
			sowing_depth: 1.0,
			sowing_distance: 15,
			pot_min_depth: 15,
			sowing_period: JSON.stringify(["March", "April", "August", "September"]),
			germination_time: "5-14 days",
			repotting_after: "N/A",
			total_growth_time: "35-50 days",
		},
	]);
}
