import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
	await knex("plant_stages").del();
	await knex("plants").del();

	await knex("plants").insert([
		{
			id: 1,
			name: "Munt",
			light: "Partial shade",
			water: "High",
			difficulty: "Easy",
			temperature: "15-25°C",
			planting_type: "both",
			image: "mint.png",
			sunlight: "partial",
			care_level: "weekly",
			temperature_min: 15,
			temperature_max: 25,
			total_days: 60,
			sowing_depth: 0.2,
			sowing_distance: 30,
			pot_min_depth: 20,
			sowing_period: JSON.stringify(["March", "April", "May"]),
			germination_time: "10-15 dagen",
			repotting_after: "3-4 weken",
			total_growth_time: "60-70 dagen",
		},
		{
			id: 2,
			name: "Tijm",
			light: "Full sun",
			water: "Low",
			difficulty: "Medium",
			temperature: "18-30°C",
			planting_type: "both",
			image: "thyme.png",
			sunlight: "full",
			care_level: "minimal",
			temperature_min: 18,
			temperature_max: 30,
			total_days: 80,
			sowing_depth: 0.1,
			sowing_distance: 25,
			pot_min_depth: 15,
			sowing_period: JSON.stringify(["April", "May"]),
			germination_time: "14-21 dagen",
			repotting_after: "4-5 weken",
			total_growth_time: "70-90 dagen",
		},
		{
			id: 3,
			name: "Rozemarijn",
			light: "Full sun",
			water: "Low",
			difficulty: "Hard",
			temperature: "15-30°C",
			planting_type: "both",
			image: "rosemary.png",
			sunlight: "full",
			care_level: "minimal",
			temperature_min: 15,
			temperature_max: 30,
			total_days: 90,
			sowing_depth: 0.3,
			sowing_distance: 40,
			pot_min_depth: 25,
			sowing_period: JSON.stringify(["April", "May"]),
			germination_time: "15-25 dagen",
			repotting_after: "5-6 weken",
			total_growth_time: "90-100 dagen",
		},
		{
			id: 4,
			name: "Bieslook",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Easy",
			temperature: "15-25°C",
			planting_type: "both",
			image: "chives.png",
			sunlight: "full",
			care_level: "weekly",
			temperature_min: 15,
			temperature_max: 25,
			total_days: 65,
			sowing_depth: 0.5,
			sowing_distance: 15,
			pot_min_depth: 15,
			sowing_period: JSON.stringify(["March", "April", "May"]),
			germination_time: "10-14 dagen",
			repotting_after: "3-4 weken",
			total_growth_time: "60-70 dagen",
		},
		{
			id: 5,
			name: "Basilicum",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Easy",
			temperature: "18-30°C",
			planting_type: "both",
			image: "basil.png",
			sunlight: "full",
			care_level: "daily",
			temperature_min: 18,
			temperature_max: 30,
			total_days: 45,
			sowing_depth: 0.3,
			sowing_distance: 25,
			pot_min_depth: 15,
			sowing_period: JSON.stringify(["April", "May", "June"]),
			germination_time: "5-10 dagen",
			repotting_after: "3-4 weken",
			total_growth_time: "30-45 dagen",
		},
		{
			id: 6,
			name: "Kerstomaatjes",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Medium",
			temperature: "18-30°C",
			planting_type: "both",
			image: "cherry-tomatoes.png",
			sunlight: "full",
			care_level: "daily",
			temperature_min: 18,
			temperature_max: 30,
			total_days: 85,
			sowing_depth: 0.5,
			sowing_distance: 50,
			pot_min_depth: 25,
			sowing_period: JSON.stringify(["March", "April", "May"]),
			germination_time: "5-10 dagen",
			repotting_after: "3-4 weken",
			total_growth_time: "60-80 dagen",
		},
		{
			id: 7,
			name: "Komkommer",
			light: "Full sun",
			water: "High",
			difficulty: "Medium",
			temperature: "20-30°C",
			planting_type: "both",
			image: "cucumber.png",
			sunlight: "full",
			care_level: "daily",
			temperature_min: 20,
			temperature_max: 30,
			total_days: 70,
			sowing_depth: 1.5,
			sowing_distance: 40,
			pot_min_depth: 30,
			sowing_period: JSON.stringify(["April", "May"]),
			germination_time: "3-7 dagen",
			repotting_after: "3-4 weken",
			total_growth_time: "50-70 dagen",
		},
		{
			id: 8,
			name: "Spinazie",
			light: "Partial shade",
			water: "Moderate",
			difficulty: "Easy",
			temperature: "10-20°C",
			planting_type: "outdoor",
			image: "spinach.png",
			sunlight: "partial",
			care_level: "weekly",
			temperature_min: 10,
			temperature_max: 20,
			total_days: 45,
			sowing_depth: 1.0,
			sowing_distance: 15,
			pot_min_depth: 15,
			sowing_period: JSON.stringify(["March", "April", "September", "October"]),
			germination_time: "7-14 dagen",
			repotting_after: "Niet van toepassing",
			total_growth_time: "40-50 dagen",
		},
		{
			id: 9,
			name: "Courgette",
			light: "Full sun",
			water: "High",
			difficulty: "Easy",
			temperature: "18-28°C",
			planting_type: "both",
			image: "zucchini.png",
			sunlight: "full",
			care_level: "daily",
			temperature_min: 18,
			temperature_max: 28,
			total_days: 55,
			sowing_depth: 2.0,
			sowing_distance: 70,
			pot_min_depth: 35,
			sowing_period: JSON.stringify(["April", "May"]),
			germination_time: "5-10 dagen",
			repotting_after: "3-4 weken",
			total_growth_time: "50-65 dagen",
		},
		{
			id: 10,
			name: "Wortel",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Easy",
			temperature: "12-22°C",
			planting_type: "outdoor",
			image: "carrot.png",
			sunlight: "full",
			care_level: "weekly",
			temperature_min: 12,
			temperature_max: 22,
			total_days: 80,
			sowing_depth: 1.0,
			sowing_distance: 5,
			pot_min_depth: 30,
			sowing_period: JSON.stringify(["March", "April", "May", "June"]),
			germination_time: "10-17 dagen",
			repotting_after: "Niet van toepassing",
			total_growth_time: "70-90 dagen",
		},
		{
			id: 11,
			name: "Radijs",
			light: "Full sun",
			water: "Moderate",
			difficulty: "Easy",
			temperature: "10-20°C",
			planting_type: "both",
			image: "radish.png",
			sunlight: "full",
			care_level: "weekly",
			temperature_min: 10,
			temperature_max: 20,
			total_days: 30,
			sowing_depth: 1.0,
			sowing_distance: 5,
			pot_min_depth: 15,
			sowing_period: JSON.stringify(["March", "April", "May", "June", "July", "August", "September"]),
			germination_time: "4-7 dagen",
			repotting_after: "Niet van toepassing",
			total_growth_time: "25-35 dagen",
		},
		{
			id: 12,
			name: "Broccoli",
			light: "Full sun",
			water: "High",
			difficulty: "Medium",
			temperature: "12-20°C",
			planting_type: "outdoor",
			image: "broccoli.png",
			sunlight: "full",
			care_level: "weekly",
			temperature_min: 12,
			temperature_max: 20,
			total_days: 80,
			sowing_depth: 1.0,
			sowing_distance: 45,
			pot_min_depth: 25,
			sowing_period: JSON.stringify(["March", "April", "May"]),
			germination_time: "5-10 dagen",
			repotting_after: "4-5 weken",
			total_growth_time: "75-90 dagen",
		},
		{
        id: 13,
        name: "Salie",
        light: "Full sun",
        water: "Low",
        difficulty: "Medium",
        temperature: "15-28°C",
        planting_type: "both",
        image: "sage.png",
        sunlight: "full",
        care_level: "minimal",
        temperature_min: 15,
        temperature_max: 28,
        total_days: 70,
        sowing_depth: 0.3,
        sowing_distance: 30,
        pot_min_depth: 20,
        sowing_period: JSON.stringify(["April", "May"]),
        germination_time: "14-21 dagen",
        repotting_after: "4-5 weken",
        total_growth_time: "60-80 dagen",
    },
    {
        id: 14,
        name: "Oregano",
        light: "Full sun",
        water: "Low",
        difficulty: "Easy",
        temperature: "15-25°C",
        planting_type: "both",
        image: "oregano.png",
        sunlight: "full",
        care_level: "minimal",
        temperature_min: 15,
        temperature_max: 25,
        total_days: 65,
        sowing_depth: 0.1,
        sowing_distance: 25,
        pot_min_depth: 15,
        sowing_period: JSON.stringify(["April", "May"]),
        germination_time: "10-15 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "50-60 dagen",
    },
    {
        id: 15,
        name: "Koriander",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "12-22°C",
        planting_type: "both",
        image: "coriander.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 22,
        total_days: 55,
        sowing_depth: 1.0,
        sowing_distance: 20,
        pot_min_depth: 20,
        sowing_period: JSON.stringify(["April", "May", "June", "September"]),
        germination_time: "10-14 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "45-55 dagen",
    },
    {
        id: 16,
        name: "Bladpeterselie",
        light: "Partial shade",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "12-22°C",
        planting_type: "both",
        image: "parsley.png",
        sunlight: "partial",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 22,
        total_days: 80,
        sowing_depth: 0.5,
        sowing_distance: 25,
        pot_min_depth: 20,
        sowing_period: JSON.stringify(["March", "April", "May"]),
        germination_time: "14-28 dagen",
        repotting_after: "4-5 weken",
        total_growth_time: "70-80 dagen",
    },
    {
        id: 17,
        name: "Dille",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "15-25°C",
        planting_type: "outdoor",
        image: "dill.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 15,
        temperature_max: 25,
        total_days: 60,
        sowing_depth: 0.5,
        sowing_distance: 20,
        pot_min_depth: 25,
        sowing_period: JSON.stringify(["April", "May", "June", "July"]),
        germination_time: "10-14 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "50-60 dagen",
    },
    {
        id: 18,
        name: "Tomaat",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "18-30°C",
        planting_type: "both",
        image: "tomato.png",
        sunlight: "full",
        care_level: "daily",
        temperature_min: 18,
        temperature_max: 30,
        total_days: 90,
        sowing_depth: 0.5,
        sowing_distance: 60,
        pot_min_depth: 30,
        sowing_period: JSON.stringify(["March", "April", "May"]),
        germination_time: "5-10 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "75-85 dagen",
    },
    {
        id: 19,
        name: "Spruitjes",
        light: "Full sun",
        water: "High",
        difficulty: "Hard",
        temperature: "10-20°C",
        planting_type: "outdoor",
        image: "brussels-sprouts.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 10,
        temperature_max: 20,
        total_days: 130,
        sowing_depth: 1.0,
        sowing_distance: 50,
        pot_min_depth: 30,
        sowing_period: JSON.stringify(["March", "April", "May"]),
        germination_time: "7-12 dagen",
        repotting_after: "4-5 weken",
        total_growth_time: "120-140 dagen",
    },
    {
        id: 20,
        name: "Witte kool",
        light: "Full sun",
        water: "High",
        difficulty: "Medium",
        temperature: "10-20°C",
        planting_type: "outdoor",
        image: "white-cabbage.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 10,
        temperature_max: 20,
        total_days: 100,
        sowing_depth: 1.0,
        sowing_distance: 50,
        pot_min_depth: 30,
        sowing_period: JSON.stringify(["April", "May", "June"]),
        germination_time: "5-10 dagen",
        repotting_after: "4-6 weken",
        total_growth_time: "90-110 dagen",
    },
    {
        id: 21,
        name: "Rode kool",
        light: "Full sun",
        water: "High",
        difficulty: "Medium",
        temperature: "10-20°C",
        planting_type: "outdoor",
        image: "red-cabbage.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 10,
        temperature_max: 20,
        total_days: 105,
        sowing_depth: 1.0,
        sowing_distance: 50,
        pot_min_depth: 30,
        sowing_period: JSON.stringify(["April", "May", "June"]),
        germination_time: "5-10 dagen",
        repotting_after: "4-6 weken",
        total_growth_time: "100-120 dagen",
    },
    {
        id: 22,
        name: "Rucola",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "10-22°C",
        planting_type: "both",
        image: "arugula.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 10,
        temperature_max: 22,
        total_days: 35,
        sowing_depth: 0.5,
        sowing_distance: 15,
        pot_min_depth: 15,
        sowing_period: JSON.stringify(["March", "April", "May", "June", "September", "October"]),
        germination_time: "3-5 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "30-40 dagen",
    },
    {
        id: 23,
        name: "Pompoen",
        light: "Full sun",
        water: "High",
        difficulty: "Medium",
        temperature: "18-28°C",
        planting_type: "outdoor",
        image: "pumpkin.png",
        sunlight: "full",
        care_level: "daily",
        temperature_min: 18,
        temperature_max: 28,
        total_days: 100,
        sowing_depth: 2.0,
        sowing_distance: 100,
        pot_min_depth: 40,
        sowing_period: JSON.stringify(["April", "May"]),
        germination_time: "5-10 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "90-110 dagen",
    },
    {
        id: 24,
        name: "Aubergine",
        light: "Full sun",
        water: "High",
        difficulty: "Hard",
        temperature: "20-30°C",
        planting_type: "both",
        image: "eggplant.png",
        sunlight: "full",
        care_level: "daily",
        temperature_min: 20,
        temperature_max: 30,
        total_days: 100,
        sowing_depth: 0.5,
        sowing_distance: 50,
        pot_min_depth: 30,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "8-15 dagen",
        repotting_after: "4-5 weken",
        total_growth_time: "90-105 dagen",
    },
	{
        id: 25,
        name: "Paprika",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "18-30°C",
        planting_type: "both",
        image: "bell-peper.png",
        sunlight: "full",
        care_level: "daily",
        temperature_min: 18,
        temperature_max: 30,
        total_days: 90,
        sowing_depth: 0.5,
        sowing_distance: 40,
        pot_min_depth: 25,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "7-14 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "70-90 dagen",
    },
    {
        id: 26,
        name: "Bloemkool",
        light: "Full sun",
        water: "High",
        difficulty: "Hard",
        temperature: "12-20°C",
        planting_type: "outdoor",
        image: "cauliflower.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 20,
        total_days: 85,
        sowing_depth: 1.0,
        sowing_distance: 50,
        pot_min_depth: 30,
        sowing_period: JSON.stringify(["April", "May", "June"]),
        germination_time: "5-10 dagen",
        repotting_after: "4-5 weken",
        total_growth_time: "75-90 dagen",
    },
    {
        id: 27,
        name: "Aardappel",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "10-22°C",
        planting_type: "outdoor",
        image: "potato.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 10,
        temperature_max: 22,
        total_days: 100,
        sowing_depth: 10.0,
        sowing_distance: 30,
        pot_min_depth: 40,
        sowing_period: JSON.stringify(["March", "April", "May"]),
        germination_time: "14-21 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "90-110 dagen",
    },
    {
        id: 28,
        name: "Knolselderij",
        light: "Full sun",
        water: "High",
        difficulty: "Hard",
        temperature: "12-22°C",
        planting_type: "outdoor",
        image: "celeriac.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 22,
        total_days: 140,
        sowing_depth: 0.2,
        sowing_distance: 35,
        pot_min_depth: 30,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "14-21 dagen",
        repotting_after: "5-6 weken",
        total_growth_time: "130-150 dagen",
    },
    {
        id: 29,
        name: "Maïs",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "16-26°C",
        planting_type: "outdoor",
        image: "corn.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 16,
        temperature_max: 26,
        total_days: 90,
        sowing_depth: 3.0,
        sowing_distance: 25,
        pot_min_depth: 35,
        sowing_period: JSON.stringify(["April", "May"]),
        germination_time: "7-10 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "80-90 dagen",
    },
    {
        id: 30,
        name: "Bosui",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "12-22°C",
        planting_type: "both",
        image: "spring-onion.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 22,
        total_days: 60,
        sowing_depth: 1.0,
        sowing_distance: 5,
        pot_min_depth: 15,
        sowing_period: JSON.stringify(["March", "April", "May", "June", "July", "August"]),
        germination_time: "10-14 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "50-70 dagen",
    },
    {
        id: 31,
        name: "Jalapeño",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "18-30°C",
        planting_type: "both",
        image: "jalapeno.png",
        sunlight: "full",
        care_level: "daily",
        temperature_min: 18,
        temperature_max: 30,
        total_days: 85,
        sowing_depth: 0.5,
        sowing_distance: 40,
        pot_min_depth: 25,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "7-14 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "70-85 dagen",
    },
    {
        id: 32,
        name: "Rode chilipeper",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "18-30°C",
        planting_type: "both",
        image: "red-chili-pepper.png",
        sunlight: "full",
        care_level: "daily",
        temperature_min: 18,
        temperature_max: 30,
        total_days: 90,
        sowing_depth: 0.5,
        sowing_distance: 40,
        pot_min_depth: 25,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "7-14 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "75-90 dagen",
    },
    {
        id: 33,
        name: "Rode ui",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "12-22°C",
        planting_type: "outdoor",
        image: "red-onion.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 22,
        total_days: 100,
        sowing_depth: 1.5,
        sowing_distance: 10,
        pot_min_depth: 20,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "10-15 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "90-110 dagen",
    },
    {
        id: 34,
        name: "Gele ui",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "12-22°C",
        planting_type: "outdoor",
        image: "yellow-onion.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 22,
        total_days: 100,
        sowing_depth: 1.5,
        sowing_distance: 10,
        pot_min_depth: 20,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "10-15 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "90-110 dagen",
    },
    {
        id: 35,
        name: "Prei",
        light: "Full sun",
        water: "High",
        difficulty: "Medium",
        temperature: "12-22°C",
        planting_type: "outdoor",
        image: "leek.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 22,
        total_days: 120,
        sowing_depth: 1.0,
        sowing_distance: 15,
        pot_min_depth: 25,
        sowing_period: JSON.stringify(["March", "April", "May"]),
        germination_time: "10-14 dagen",
        repotting_after: "5-6 weken",
        total_growth_time: "100-130 dagen",
    },
    {
        id: 36,
        name: "Doperwten",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "10-18°C",
        planting_type: "outdoor",
        image: "peas.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 10,
        temperature_max: 18,
        total_days: 65,
        sowing_depth: 2.5,
        sowing_distance: 10,
        pot_min_depth: 20,
        sowing_period: JSON.stringify(["March", "April", "May"]),
        germination_time: "7-14 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "60-75 dagen",
    },
	{
        id: 37,
        name: "Pastinaak",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "10-20°C",
        planting_type: "outdoor",
        image: "parsnip.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 10,
        temperature_max: 20,
        total_days: 120,
        sowing_depth: 1.5,
        sowing_distance: 15,
        pot_min_depth: 35,
        sowing_period: JSON.stringify(["March", "April", "May"]),
        germination_time: "14-25 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "110-130 dagen",
    },
    {
        id: 38,
        name: "Rettich",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "12-22°C",
        planting_type: "outdoor",
        image: "daikon.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 22,
        total_days: 60,
        sowing_depth: 1.5,
        sowing_distance: 15,
        pot_min_depth: 30,
        sowing_period: JSON.stringify(["April", "May", "June", "July", "August"]),
        germination_time: "5-10 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "50-65 dagen",
    },
    {
        id: 39,
        name: "Koolrabi",
        light: "Full sun",
        water: "High",
        difficulty: "Easy",
        temperature: "12-20°C",
        planting_type: "both",
        image: "kohlrabi.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 20,
        total_days: 65,
        sowing_depth: 1.0,
        sowing_distance: 30,
        pot_min_depth: 25,
        sowing_period: JSON.stringify(["March", "April", "May", "June"]),
        germination_time: "5-10 dagen",
        repotting_after: "4-5 weken",
        total_growth_time: "55-70 dagen",
    },
    {
        id: 40,
        name: "Groene chilipeper",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "18-30°C",
        planting_type: "both",
        image: "green-chili-pepper.png",
        sunlight: "full",
        care_level: "daily",
        temperature_min: 18,
        temperature_max: 30,
        total_days: 80,
        sowing_depth: 0.5,
        sowing_distance: 40,
        pot_min_depth: 25,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "7-14 dagen",
        repotting_after: "3-4 weken",
        total_growth_time: "70-85 dagen",
    },
    {
        id: 41,
        name: "Zoete aardappel",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Medium",
        temperature: "20-30°C",
        planting_type: "outdoor",
        image: "sweet-potato.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 20,
        temperature_max: 30,
        total_days: 110,
        sowing_depth: 8.0,
        sowing_distance: 40,
        pot_min_depth: 40,
        sowing_period: JSON.stringify(["April", "May"]),
        germination_time: "10-20 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "100-120 dagen",
    },
    {
        id: 42,
        name: "Rode biet",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "12-20°C",
        planting_type: "outdoor",
        image: "beetroot.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 12,
        temperature_max: 20,
        total_days: 70,
        sowing_depth: 2.0,
        sowing_distance: 10,
        pot_min_depth: 20,
        sowing_period: JSON.stringify(["April", "May", "June", "July"]),
        germination_time: "7-14 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "60-80 dagen",
    },
    {
        id: 43,
        name: "Bleekselderij",
        light: "Full sun",
        water: "High",
        difficulty: "Hard",
        temperature: "15-22°C",
        planting_type: "both",
        image: "celery.png",
        sunlight: "full",
        care_level: "daily",
        temperature_min: 15,
        temperature_max: 22,
        total_days: 120,
        sowing_depth: 0.2,
        sowing_distance: 30,
        pot_min_depth: 25,
        sowing_period: JSON.stringify(["March", "April"]),
        germination_time: "14-21 dagen",
        repotting_after: "5-6 weken",
        total_growth_time: "110-130 dagen",
    },
    {
        id: 44,
        name: "Raap",
        light: "Full sun",
        water: "Moderate",
        difficulty: "Easy",
        temperature: "10-18°C",
        planting_type: "outdoor",
        image: "turnip.png",
        sunlight: "full",
        care_level: "weekly",
        temperature_min: 10,
        temperature_max: 18,
        total_days: 50,
        sowing_depth: 1.0,
        sowing_distance: 15,
        pot_min_depth: 20,
        sowing_period: JSON.stringify(["March", "April", "August", "September"]),
        germination_time: "5-10 dagen",
        repotting_after: "Niet van toepassing",
        total_growth_time: "45-60 dagen",
    },
	]);
}
