import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
	await knex("plant_stages").del();

	const stages = [
		// Tomaat (plant_id: 1) — matches frontend mock: Zaaien(7), Kiem(14), Blad(21), Groeispurt(21), Bloei(14), Oogst(13) = 90
		{ plant_id: 1, stage_name: "Zaaien", stage_order: 1, duration_days: 7, thresholds: JSON.stringify({ temp_min: 18, temp_max: 30, soil_moist_min: 60, soil_moist_max: 90 }), validation_description: "Seed has sprouted and first cotyledons are visible", requirements: JSON.stringify({ light: "Indirect", water: "Keep moist" }), instructions: JSON.stringify(["Keep soil consistently moist", "Provide indirect light", "Maintain temperature 18-30°C"]) },
		{ plant_id: 1, stage_name: "Kiem", stage_order: 2, duration_days: 14, thresholds: JSON.stringify({ temp_min: 18, temp_max: 28, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "True leaves have developed on the seedling", requirements: JSON.stringify({ light: "Partial sun", water: "Moderate" }), instructions: JSON.stringify(["Transplant to larger pot if needed", "Start introducing direct sunlight gradually", "Water when top soil feels dry"]) },
		{ plant_id: 1, stage_name: "Blad", stage_order: 3, duration_days: 21, thresholds: JSON.stringify({ temp_min: 18, temp_max: 30, soil_moist_min: 40, soil_moist_max: 75 }), validation_description: "Plant has multiple mature leaves and is growing rapidly", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Provide full sun (6-8 hours)", "Fertilize weekly with balanced fertilizer", "Stake or cage the plant for support"]) },
		{ plant_id: 1, stage_name: "Groeispurt", stage_order: 4, duration_days: 21, thresholds: JSON.stringify({ temp_min: 18, temp_max: 30, soil_moist_min: 40, soil_moist_max: 75 }), validation_description: "Plant is growing rapidly with abundant foliage", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Water consistently", "Continue weekly fertilization", "Remove lower yellowing leaves"]) },
		{ plant_id: 1, stage_name: "Bloei", stage_order: 5, duration_days: 14, thresholds: JSON.stringify({ temp_min: 18, temp_max: 30, soil_moist_min: 40, soil_moist_max: 75 }), validation_description: "Yellow flowers have appeared on the plant", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Continue full sun exposure", "Reduce nitrogen fertilizer", "Encourage pollination by gently shaking flowers"]) },
		{ plant_id: 1, stage_name: "Oogst", stage_order: 6, duration_days: 13, thresholds: JSON.stringify({ temp_min: 18, temp_max: 30, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Fruits are fully colored and slightly soft to the touch", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Water consistently to prevent cracking", "Harvest when fully colored and slightly soft", "Remove yellowing lower leaves"]) },

		// Kool (plant_id: 2) — matches frontend mock: Zaaien(10), Kiem(15), Blad(25), Groeispurt(20), Oogst(15) = 85
		{ plant_id: 2, stage_name: "Zaaien", stage_order: 1, duration_days: 10, thresholds: JSON.stringify({ temp_min: 10, temp_max: 20, soil_moist_min: 60, soil_moist_max: 90 }), validation_description: "Seed has sprouted and first leaves appear", requirements: JSON.stringify({ light: "Indirect", water: "Keep moist" }), instructions: JSON.stringify(["Keep soil consistently moist", "Provide indirect light", "Maintain temperature 10-20°C"]) },
		{ plant_id: 2, stage_name: "Kiem", stage_order: 2, duration_days: 15, thresholds: JSON.stringify({ temp_min: 10, temp_max: 20, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Seedling has 3-4 true leaves", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Transplant outdoors after frost danger passes", "Space plants 45cm apart", "Water regularly"]) },
		{ plant_id: 2, stage_name: "Blad", stage_order: 3, duration_days: 25, thresholds: JSON.stringify({ temp_min: 10, temp_max: 20, soil_moist_min: 50, soil_moist_max: 85 }), validation_description: "Outer leaves are large and head formation is beginning", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Water deeply 2-3 times per week", "Apply mulch to retain moisture", "Fertilize with nitrogen-rich fertilizer"]) },
		{ plant_id: 2, stage_name: "Groeispurt", stage_order: 4, duration_days: 20, thresholds: JSON.stringify({ temp_min: 10, temp_max: 20, soil_moist_min: 60, soil_moist_max: 85 }), validation_description: "A dense head is forming in the center of the plant", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Maintain consistent watering", "Protect from pests with netting", "Monitor for slugs and snails"]) },
		{ plant_id: 2, stage_name: "Oogst", stage_order: 5, duration_days: 15, thresholds: JSON.stringify({ temp_min: 5, temp_max: 15, soil_moist_min: 40, soil_moist_max: 70 }), validation_description: "Cabbage head is firm and fully formed", requirements: JSON.stringify({ light: "Full sun", water: "Reduced" }), instructions: JSON.stringify(["Harvest before heads split", "Cut head at base with a sharp knife", "Store in cool place"]) },

		// Basilicum (plant_id: 3)
		{ plant_id: 3, stage_name: "Zaaien", stage_order: 1, duration_days: 7, thresholds: JSON.stringify({ temp_min: 18, temp_max: 30, soil_moist_min: 60, soil_moist_max: 90 }), validation_description: "Seed has sprouted and cotyledons are visible", requirements: JSON.stringify({ light: "Indirect", water: "Keep moist" }), instructions: JSON.stringify(["Keep soil warm and moist", "Provide bright indirect light", "Maintain temperature 18-30°C"]) },
		{ plant_id: 3, stage_name: "Kiem", stage_order: 2, duration_days: 10, thresholds: JSON.stringify({ temp_min: 18, temp_max: 28, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Seedling has 2-3 sets of true leaves", requirements: JSON.stringify({ light: "Full sun", water: "Moderate" }), instructions: JSON.stringify(["Gradually introduce to full sun", "Pinch off top leaves to encourage bushiness", "Water when soil feels dry"]) },
		{ plant_id: 3, stage_name: "Blad", stage_order: 3, duration_days: 14, thresholds: JSON.stringify({ temp_min: 18, temp_max: 30, soil_moist_min: 40, soil_moist_max: 75 }), validation_description: "Plant is bushy with abundant leaves", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Harvest leaves from top down", "Remove flower buds to prolong growth", "Fertilize monthly"]) },

		// Sla (plant_id: 4)
		{ plant_id: 4, stage_name: "Zaaien", stage_order: 1, duration_days: 7, thresholds: JSON.stringify({ temp_min: 10, temp_max: 20, soil_moist_min: 60, soil_moist_max: 90 }), validation_description: "Seed has sprouted and first leaves appear", requirements: JSON.stringify({ light: "Indirect", water: "Keep moist" }), instructions: JSON.stringify(["Keep soil moist", "Provide indirect light", "Maintain temperature 10-20°C"]) },
		{ plant_id: 4, stage_name: "Kiem", stage_order: 2, duration_days: 10, thresholds: JSON.stringify({ temp_min: 10, temp_max: 20, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Seedling has 3-4 true leaves", requirements: JSON.stringify({ light: "Partial shade", water: "Regular" }), instructions: JSON.stringify(["Thin seedlings to 30cm apart", "Water regularly", "Provide partial shade in hot weather"]) },
		{ plant_id: 4, stage_name: "Blad", stage_order: 3, duration_days: 14, thresholds: JSON.stringify({ temp_min: 10, temp_max: 20, soil_moist_min: 50, soil_moist_max: 85 }), validation_description: "Leaves are forming a loose head or rosette", requirements: JSON.stringify({ light: "Partial shade", water: "Regular" }), instructions: JSON.stringify(["Water consistently to prevent bitterness", "Harvest outer leaves as needed", "Harvest whole head when mature"]) },
		{ plant_id: 4, stage_name: "Oogst", stage_order: 4, duration_days: 14, thresholds: JSON.stringify({ temp_min: 5, temp_max: 20, soil_moist_min: 40, soil_moist_max: 70 }), validation_description: "Leaves are large and ready for harvest", requirements: JSON.stringify({ light: "Partial shade", water: "Reduced" }), instructions: JSON.stringify(["Harvest early morning for best crispness", "Cut outer leaves first", "Refrigerate immediately"]) },

		// Aardbei (plant_id: 5)
		{ plant_id: 5, stage_name: "Zaaien", stage_order: 1, duration_days: 14, thresholds: JSON.stringify({ temp_min: 15, temp_max: 25, soil_moist_min: 60, soil_moist_max: 90 }), validation_description: "Seed has sprouted and first leaves appear", requirements: JSON.stringify({ light: "Indirect", water: "Keep moist" }), instructions: JSON.stringify(["Keep soil consistently moist", "Provide bright indirect light", "Maintain temperature 15-25°C"]) },
		{ plant_id: 5, stage_name: "Kiem", stage_order: 2, duration_days: 14, thresholds: JSON.stringify({ temp_min: 15, temp_max: 25, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Seedling has several true leaves", requirements: JSON.stringify({ light: "Full sun", water: "Moderate" }), instructions: JSON.stringify(["Transplant to final location", "Space plants 35cm apart", "Water at base to prevent leaf diseases"]) },
		{ plant_id: 5, stage_name: "Blad", stage_order: 3, duration_days: 14, thresholds: JSON.stringify({ temp_min: 15, temp_max: 25, soil_moist_min: 40, soil_moist_max: 75 }), validation_description: "Plant is producing runners and leaves", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Remove runners to focus energy on fruit", "Apply straw mulch around plants", "Fertilize with balanced fertilizer"]) },
		{ plant_id: 5, stage_name: "Bloei", stage_order: 4, duration_days: 10, thresholds: JSON.stringify({ temp_min: 15, temp_max: 25, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "White flowers have appeared on the plant", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Ensure good air circulation", "Water regularly", "Protect from heavy rain"]) },
		{ plant_id: 5, stage_name: "Oogst", stage_order: 5, duration_days: 14, thresholds: JSON.stringify({ temp_min: 15, temp_max: 25, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Red fruits are visible and ripening", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Harvest when fully red", "Pick regularly to encourage more fruit", "Watch for slugs and birds"]) },

		// Wortel (plant_id: 6)
		{ plant_id: 6, stage_name: "Zaaien", stage_order: 1, duration_days: 14, thresholds: JSON.stringify({ temp_min: 10, temp_max: 25, soil_moist_min: 60, soil_moist_max: 90 }), validation_description: "Seed has sprouted and first leaves appear", requirements: JSON.stringify({ light: "Indirect", water: "Keep moist" }), instructions: JSON.stringify(["Keep soil moist during germination", "Provide indirect light", "Be patient - carrots can take 2-3 weeks"]) },
		{ plant_id: 6, stage_name: "Kiem", stage_order: 2, duration_days: 14, thresholds: JSON.stringify({ temp_min: 10, temp_max: 25, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Seedling has feathery true leaves", requirements: JSON.stringify({ light: "Full sun", water: "Moderate" }), instructions: JSON.stringify(["Thin seedlings to 10cm apart", "Water regularly", "Remove weeds carefully"]) },
		{ plant_id: 6, stage_name: "Blad", stage_order: 3, duration_days: 21, thresholds: JSON.stringify({ temp_min: 10, temp_max: 25, soil_moist_min: 40, soil_moist_max: 75 }), validation_description: "Leafy tops are lush and root is thickening", requirements: JSON.stringify({ light: "Full sun", water: "Regular" }), instructions: JSON.stringify(["Water deeply to encourage root growth", "Avoid high nitrogen fertilizer", "Thin if overcrowded"]) },
		{ plant_id: 6, stage_name: "Oogst", stage_order: 4, duration_days: 21, thresholds: JSON.stringify({ temp_min: 5, temp_max: 20, soil_moist_min: 40, soil_moist_max: 70 }), validation_description: "Carrots are fully sized and ready for harvest", requirements: JSON.stringify({ light: "Full sun", water: "Reduced" }), instructions: JSON.stringify(["Harvest when roots are 2cm in diameter", "Loosen soil before pulling", "Store in cool damp place"]) },

		// Munt (plant_id: 7)
		{ plant_id: 7, stage_name: "Zaaien", stage_order: 1, duration_days: 10, thresholds: JSON.stringify({ temp_min: 15, temp_max: 25, soil_moist_min: 60, soil_moist_max: 90 }), validation_description: "Seed has sprouted and first leaves appear", requirements: JSON.stringify({ light: "Indirect", water: "Keep moist" }), instructions: JSON.stringify(["Keep soil moist", "Provide indirect light", "Maintain temperature 15-25°C"]) },
		{ plant_id: 7, stage_name: "Kiem", stage_order: 2, duration_days: 10, thresholds: JSON.stringify({ temp_min: 15, temp_max: 25, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Seedling has several true leaves", requirements: JSON.stringify({ light: "Partial shade", water: "Regular" }), instructions: JSON.stringify(["Transplant to container or garden", "Space plants 45cm apart", "Water regularly"]) },
		{ plant_id: 7, stage_name: "Blad", stage_order: 3, duration_days: 21, thresholds: JSON.stringify({ temp_min: 15, temp_max: 25, soil_moist_min: 40, soil_moist_max: 75 }), validation_description: "Plant is spreading with abundant aromatic leaves", requirements: JSON.stringify({ light: "Partial shade", water: "Regular" }), instructions: JSON.stringify(["Harvest leaves regularly", "Cut back to encourage fresh growth", "Use containers to control spreading"]) },
		{ plant_id: 7, stage_name: "Oogst", stage_order: 4, duration_days: 14, thresholds: JSON.stringify({ temp_min: 10, temp_max: 25, soil_moist_min: 40, soil_moist_max: 70 }), validation_description: "Leaves are abundant and ready for continuous harvest", requirements: JSON.stringify({ light: "Partial shade", water: "Regular" }), instructions: JSON.stringify(["Harvest by cutting stems above leaf pair", "Never harvest more than 1/3 of plant", "Use fresh or dry for storage"]) },

		// Spinazie (plant_id: 8)
		{ plant_id: 8, stage_name: "Zaaien", stage_order: 1, duration_days: 7, thresholds: JSON.stringify({ temp_min: 5, temp_max: 20, soil_moist_min: 60, soil_moist_max: 90 }), validation_description: "Seed has sprouted and first leaves appear", requirements: JSON.stringify({ light: "Indirect", water: "Keep moist" }), instructions: JSON.stringify(["Keep soil moist", "Provide indirect light", "Maintain temperature 5-20°C"]) },
		{ plant_id: 8, stage_name: "Kiem", stage_order: 2, duration_days: 10, thresholds: JSON.stringify({ temp_min: 5, temp_max: 20, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Seedling has 3-4 true leaves", requirements: JSON.stringify({ light: "Partial shade", water: "Regular" }), instructions: JSON.stringify(["Thin seedlings to 15cm apart", "Water regularly", "Provide shade in warm weather"]) },
		{ plant_id: 8, stage_name: "Blad", stage_order: 3, duration_days: 14, thresholds: JSON.stringify({ temp_min: 5, temp_max: 20, soil_moist_min: 50, soil_moist_max: 80 }), validation_description: "Leaves are large and ready for harvesting", requirements: JSON.stringify({ light: "Partial shade", water: "Regular" }), instructions: JSON.stringify(["Harvest outer leaves first", "Keep soil moist to prevent bolting", "Sow new seeds every 2 weeks for continuous harvest"]) },
		{ plant_id: 8, stage_name: "Oogst", stage_order: 4, duration_days: 14, thresholds: JSON.stringify({ temp_min: 5, temp_max: 20, soil_moist_min: 40, soil_moist_max: 70 }), validation_description: "Leaves are fully mature and ready for final harvest", requirements: JSON.stringify({ light: "Partial shade", water: "Reduced" }), instructions: JSON.stringify(["Harvest before flower stalks appear", "Wash thoroughly before eating", "Refrigerate in damp paper towel"]) },
	];

	await knex("plant_stages").insert(stages);
}
